local t = require("tests.test_runner")
local utils = require("notebook.utils")

t.describe("utils.generate_cell_id", function()
    t.it("generates unique IDs", function()
        local id1 = utils.generate_cell_id()
        local id2 = utils.generate_cell_id()
        t.neq(id1, id2)
    end)

    t.it("starts with 'cell_' prefix", function()
        local id = utils.generate_cell_id()
        t.matches("^cell_", id)
    end)
end)

t.describe("utils.parse_separator", function()
    t.it("parses code cell", function()
        local cell_type, cell_id = utils.parse_separator("# %%")
        t.eq("code", cell_type)
        t.is_nil(cell_id)
    end)

    t.it("parses markdown cell", function()
        local cell_type, cell_id = utils.parse_separator("# %% [markdown]")
        t.eq("markdown", cell_type)
        t.is_nil(cell_id)
    end)

    t.it("parses cell with ID", function()
        local cell_type, cell_id = utils.parse_separator("# %% id:cell_123_456")
        t.eq("code", cell_type)
        t.eq("cell_123_456", cell_id)
    end)

    t.it("parses markdown cell with ID", function()
        local cell_type, cell_id = utils.parse_separator("# %% [markdown] id:abc123")
        t.eq("markdown", cell_type)
        t.eq("abc123", cell_id)
    end)
end)

t.describe("utils.build_separator", function()
    t.it("builds code cell separator", function()
        local sep = utils.build_separator("code", nil)
        t.eq("# %%", sep)
    end)

    t.it("builds markdown cell separator", function()
        local sep = utils.build_separator("markdown", nil)
        t.eq("# %% [markdown]", sep)
    end)

    t.it("includes cell ID", function()
        local sep = utils.build_separator("code", "cell_123")
        t.eq("# %% id:cell_123", sep)
    end)

    t.it("builds markdown separator with ID", function()
        local sep = utils.build_separator("markdown", "cell_456")
        t.eq("# %% [markdown] id:cell_456", sep)
    end)
end)

t.describe("utils.format_elapsed", function()
    t.it("returns empty string for nil", function()
        t.eq("", utils.format_elapsed(nil))
    end)

    t.it("formats sub-second as milliseconds", function()
        local result = utils.format_elapsed(0.234)
        t.matches("234ms", result)
    end)

    t.it("formats seconds with two decimals", function()
        local result = utils.format_elapsed(5.67)
        t.matches("5%.67s", result)
    end)

    t.it("formats minutes and seconds", function()
        local result = utils.format_elapsed(125.3)
        t.matches("2m", result)
    end)
end)
